image: hseeberger/scala-sbt:8u222_1.3.4_2.13.1

cache:
  paths:
    - /home/sbtuser/.ivy2/
    - /home/sbtuser/.sbt/
    - /home/sbtuser/.cache/

variables:
  DISPLAY: ':178'
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none
#  GET_SOURCES_ATTEMPTS: 3

stages:
  - validate
  - publish

before_script:
  - apt update
  - apt install --no-install-recommends -y libjava-gnome-java xvfb
  - find / -name gtk.jar 2>/dev/null
  - Xvfb $DISPLAY &

tests:
  stage: validate
  script:
    - sbt -v +validate

release:
  stage: publish
  before_script:
    - apt install --no-install-recommends -y dnsutils netcat-openbsd
    - printenv | grep '^[A-Z][A-Z_]*=.*' | grep -v '^_..*' | sort
  only:
    - master
  script:
    - mkdir ~/.ssh
    - ssh-keyscan -H -p 22 gitlab.com > ~/.ssh/known_hosts
    - echo "${_SSH_DEPLOY_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 0400 ~/.ssh/*
    - git config user.name "Gitlab CI"
    - git config user.email $GITLAB_USER_EMAIL
    - git checkout $CI_COMMIT_REF_NAME
    - git remote set-url --push origin $(perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#' <<< $CI_REPOSITORY_URL)
    - git config --list
    - sbt -v -Dbintray.user=$BINTRAY_USER -Dbintray.pass=${_BINTRAY_PASS} "release with-defaults"

  after_script:
    - rm -Rfv .ssh