image: hseeberger/scala-sbt

cache:
  paths:
    - $PWD/.ivy2/
    - $PWD/.sbt/

variables:
  DISPLAY: :178
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none
#  GET_SOURCES_ATTEMPTS: 3

stages:
  - validate
  - publish

before_script:
  - apt update
  - apt install dnsutils netcat-openbsd --no-install-recommends libjava-gnome-java xvfb -y
  - printenv | grep '^[A-Z][A-Z_]*=.*' | grep -v '^_..*' | sort
  - Xvfb :178 &

tests:
  stage: validate
  script:
    - sbt -ivy $PWD/.ivy2 -sbt-dir $PWD/.sbt validate

release:
  stage: publish
  only:
    - master
  script:
    - env | sort
    - mkdir ~/.ssh
    - ssh-keyscan -H -p 22 gitlab.com > ~/.ssh/known_hosts
    - echo "${_SSH_DEPLOY_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 0400 ~/.ssh/*
    - git config user.name "Gitlab CI"
    - git config user.email $GITLAB_USER_EMAIL
    - git checkout $CI_COMMIT_REF_NAME
    - git remote set-url --push origin $(perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#' <<< $CI_REPOSITORY_URL)
    - git config --list
    - sbt -ivy $PWD/.ivy2 -sbt-dir $PWD/.sbt -Dbintray.user=$BINTRAY_USER -Dbintray.pass=${_BINTRAY_PASS} "release with-defaults"

  after_script:
    - rm -Rfv .ssh